FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o api ./cmd/server

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/api /app/api
COPY --from=builder /app/internal/email/templates /app/internal/email/templates
EXPOSE 8080
CMD ["/app/api"]